# Generated by Django 5.2.4 on 2025-07-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('month_name', models.CharField(max_length=20)),
                ('day_of_month', models.IntegerField()),
                ('weekday_number', models.IntegerField()),
                ('weekday_name', models.CharField(max_length=20)),
                ('quarter_number', models.IntegerField(blank=True, null=True)),
                ('quarter_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dim Dates',
                'db_table': 'dimdate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDiscipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=50, unique=True)),
                ('discipline_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dim Disciplines',
                'db_table': 'dimdiscipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Dim Materials',
                'db_table': 'dimmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_type', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('is_calibrated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Dim Tools',
                'db_table': 'dimtool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactInventoryTransactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fact Inventory Transactions',
                'db_table': 'factinventorytransactions',
                'managed': False,
            },
        ),
    ]
